image: node:12.10

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

services:
  - mongo
  - redis

variables:
  DB_PATH: ''
  REDIS_PATH: 'redis'
  NODE_ENV: test

check_code:
  script:
  - npm install -g mocha
  - npm install
  - npm run lint
